const C='game-museum-v3-5-3-nintendo-sega-v2',A=[
'./','./index.html','./styles.css','./app.js','./data.js','./haul-update-2026-08-12.js','./nintendo-ds-update.js','./nintendo-sega-update.js?v=1','./filter-order.js?v=2','./manifest.webmanifest','./icon-192.png','./icon-512.png',
'./assets/covers/nfs.jpg','./assets/covers/mafia.jpg','./assets/covers/gta.jpg','./assets/covers/fc25.jpg','./assets/covers/fc24.jpg','./assets/covers/charlie-and-the-chocolate-factory-ps2.jpg','./assets/archive/charlie-and-the-chocolate-factory-ps2-original.jpg',
'./assets/covers/grand-theft-auto-2-ps1.jpg','./assets/covers/tomb-raider-ps1.jpg','./assets/covers/tomb-raider-iii-ps1.jpg','./assets/archive/grand-theft-auto-2-ps1-original.jpg','./assets/archive/tomb-raider-ps1-original.jpg','./assets/archive/tomb-raider-iii-ps1-original.jpg',
'./assets/covers/fifa-08-ps2.jpg','./assets/archive/fifa-08-ps2-original.jpg','./assets/covers/hogwarts-legacy-ps4.jpg','./assets/archive/hogwarts-legacy-ps4-original.jpg','./assets/covers/efootball-pes-2020-celtic-fc-edition-ps4.jpg','./assets/archive/efootball-pes-2020-celtic-fc-edition-ps4-original.jpg','./assets/covers/fifa-15-ps4.webp','./assets/archive/fifa-15-ps4-original.jpg',
'./assets/covers/call-of-duty-modern-warfare-mobilized-ds.jpg','./assets/archive/call-of-duty-modern-warfare-mobilized-ds-original.jpg','./assets/covers/cars-ds.jpg','./assets/archive/cars-ds-original.jpg','./assets/covers/scooby-doo-whos-watching-who-ds.jpg','./assets/archive/scooby-doo-whos-watching-who-ds-original.jpg','./assets/covers/new-super-mario-bros-ds.jpg','./assets/archive/new-super-mario-bros-ds-original.jpg','./assets/covers/mario-sonic-olympic-games-ds.jpg','./assets/archive/mario-sonic-olympic-games-ds-original.jpg',
'./assets/covers/fifa-22-switch.jpg','./assets/archive/fifa-22-switch-original.jpg','./assets/covers/little-friends-dogs-cats-switch.webp','./assets/archive/little-friends-dogs-cats-switch-original.jpg','./assets/covers/mario-kart-8-deluxe-switch.jpg','./assets/archive/mario-kart-8-deluxe-switch-original.jpg','./assets/covers/minecraft-switch.jpg','./assets/archive/minecraft-switch-original.jpg','./assets/covers/need-for-speed-hot-pursuit-remastered-switch.jpg','./assets/archive/need-for-speed-hot-pursuit-remastered-switch-original.jpg','./assets/covers/new-super-mario-bros-u-deluxe-switch.jpg','./assets/archive/new-super-mario-bros-u-deluxe-switch-original.jpg','./assets/covers/super-mario-galaxy-1-2-switch.jpg','./assets/archive/super-mario-galaxy-1-2-switch-original.jpg',
'./assets/covers/super-mario-galaxy-wii.jpg','./assets/archive/super-mario-galaxy-wii-original.jpg','./assets/covers/super-mario-galaxy-2-wii.webp','./assets/archive/super-mario-galaxy-2-wii-original.jpg','./assets/covers/f1-2009-wii.jpg','./assets/archive/f1-2009-wii-original.jpg',
'./assets/covers/sonic-the-hedgehog-mega-drive.webp','./assets/archive/sonic-the-hedgehog-mega-drive-original.jpg'
];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(C).then(x=>x.addAll(A)))});
self.addEventListener('activate',e=>e.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x))))])));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{let z=r.clone();caches.open(C).then(x=>x.put(e.request,z));return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match('./index.html'))))});
